### ISSUE TITLE
Rotation vector for head

### ISSUE THREAD

**Issue by farhad-dalirani** [eyeware/eyeware-ros#3]
Hello,

(A) First question:
==========================================================================
1: The rotation vector for the head is X Y Z W. I do not understand it, can you explain it more?
What is the name of this notion for rotation?

2: How can I convert it to a rotation matrix?

(B) Second question:
==========================================================================
Can you refer me to a place about coordinate systems in GazeSense?

1: head coordinate system. We have a transition and rotation vector for the head, which means we have a coordinate system for the head.

2: we have positions of the left and right eyes. Are they in the coordinate system of the head?

3: Where is the world coordinate system? Is it the RealSense Camera?

**Comment by gsaponaro** [comment]
Hi @farhad-dalirani, sorry for the delayed answer, some of us were on holiday.

First of all, can you confirm whether you have received the **GazeSense User Guide** (pdf with around 40 pages)?

Please find some answers below, let us know if they are OK to proceed.

**A.1**

The GazeSense ROS bridge publishes rotation data as **quaternions**, following ROS standard practices. Please check out [this ROS tutorial](http://wiki.ros.org/tf2/Tutorials/Quaternions) and the links contained therein.

**A.2**

The [ROS tf.transformations](https://docs.ros.org/en/kinetic/api/tf/html/python/transformations.html) library seems adequate for doing the conversions that you want. It supports rotation matrices, Euler angles and other ways of expressing rotations.

Also note that:
* Rotation matrices are internally computed by our technology from a triplet of rotation angles in radians along the **ZXY** axes of the World Coordinate System, respectively. See also [Euler angles](https://en.wikipedia.org/wiki/Euler_angles) (ZXY convention) and [Rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix).

* The GazeSense application and its original Python API (without the ROS layer) publish data as rotation matrices. For the ROS bridge, we internally convert them to quaternions with the method `gs_head_pose_info_to_msg` from `gazesense_bridge/scripts/utils.py` - check it out, it could give you pointers on obtaining rotation matrices and verifying that your conversion is correct.

* Another option would be to obtain rotation matrices directly from the GazeSense Python API, bypassing ROS: check out how `head_pose.transform.rotation` is used in `client_sample.py` from your GazeSense folder.

**B**

- In general, please check out the GazeSense User Guide, Section 17. Advanced Information about Units and 3D Geometry.
- Note that you are using what we call "GazeSense app" (the graphical application, plus the ROS bridge as an extra layer), not "GazeSense SDK" (which is a different product).

**B.1**

Indeed, you can think (and do calculations) in terms of a coordinate system located on the head. However, note that our software publishes everything in terms of World Coordinate System (see next point).

**B.2**

In our API, eye positions are expressed in the World Coordinate System. Instead, if you want to refer them to the head, you have to apply the head rotation and translation yourself.

**B.3**

Our algorithm provides metric positions expressed with respect to a World Coordinate System **arbitrarily defined by the user**.

In the available Setups shown in GazeSense app, such as the "Blank" Setup, the World Coordinate System is **by default located on a virtual floor**, which means translated along the y axis by 1.2 meters with respect to the camera, like in this picture:

![wcs](https://user-images.githubusercontent.com/6716962/181483414-96dfc6bd-771e-4ff1-aaf3-2e250c9e146d.png)

**Comment by farhad-dalirani** [comment]
Thank you, @gsaponaro, for the detailed answer.
