### ISSUE TITLE
Gaze vectors intersect each other at close distance

### ISSUE THREAD

**Issue by farhad-dalirani** [eyeware/eyeware-ros#4]
Hello,

I installed a RealSense camera on a car, and with the use of your application, I collected some data. During collecting the data, I was behind the wheel of the car and a was looking at a wall at a distance of 5 meters. 

I read a person's topic (head, left eye, and right eye) and draw left and right eye locations. The image is as follows:
![Screenshot from 2022-07-16 20-12-47](https://user-images.githubusercontent.com/65308831/179375857-323ec4f0-e52e-4258-8439-72107c4f2bb7.png)

For the beginning of two lines, I get left and right eye positions; for the end of lines, I add the left and right eyes' positions with the left and right eyes' direction vector.

 The problem is that since I was behind the wheel and I was looking at a wall with a 5-meter distance to me, I was expecting the intersection of two lines to be further, not in a range of less than one unit from the eyes position. It confused me.

The code for drawing:
```
        left_eye_x_start = person.tracking_info.gaze.left_eye_ray.origin.x
        left_eye_x_end = person.tracking_info.gaze.left_eye_ray.origin.x + person.tracking_info.gaze.left_eye_ray.direction.x

        left_eye_y_start = person.tracking_info.gaze.left_eye_ray.origin.y
        left_eye_y_end = person.tracking_info.gaze.left_eye_ray.origin.y + person.tracking_info.gaze.left_eye_ray.direction.y

        left_eye_z_start = person.tracking_info.gaze.left_eye_ray.origin.z
        left_eye_z_end = person.tracking_info.gaze.left_eye_ray.origin.z + person.tracking_info.gaze.left_eye_ray.direction.z

        right_eye_x_start = person.tracking_info.gaze.right_eye_ray.origin.x
        right_eye_x_end = person.tracking_info.gaze.right_eye_ray.origin.x + person.tracking_info.gaze.right_eye_ray.direction.x

        right_eye_y_start = person.tracking_info.gaze.right_eye_ray.origin.y
        right_eye_y_end = person.tracking_info.gaze.right_eye_ray.origin.y + person.tracking_info.gaze.right_eye_ray.direction.y

        right_eye_z_start = person.tracking_info.gaze.right_eye_ray.origin.z
        right_eye_z_end = person.tracking_info.gaze.right_eye_ray.origin.z + person.tracking_info.gaze.right_eye_ray.direction.z

        ax.plot3D([left_eye_x_start, left_eye_x_end], [left_eye_y_start, left_eye_y_end], [left_eye_z_start, left_eye_z_end], 'red', label='left')
        ax.scatter(left_eye_x_start, left_eye_y_start, left_eye_z_start, marker='o')
        ax.plot3D([right_eye_x_start, right_eye_x_end], [right_eye_y_start, right_eye_y_end], [right_eye_z_start, right_eye_z_end], 'blue', label='right')
        ax.scatter(right_eye_x_start, right_eye_y_start, right_eye_z_start, marker='^')

```

**Comment by kenneth-ew** [comment]
Hi Farhard,

Your assumptions are correct. In theory the lines of sight should intersect further.

The challenge is that the eye tracking system does not have perfect accuracy. A few degrees of error, which are not uncommon, would lead to the early intersection. Unfortunately that would remain as noise in your data and I hope the data is nevertheless still valuable, as accurately obtaining that intersection may be very challenging for any eye tracking system.

If you need higher accuracy, calibration will reduce the errors. I don't know if you did that? In an automotive application it can be difficult to obtain calibration data from driver/passengers, but in your lab setting, calibration would be recommended.

**Comment by gsaponaro** [comment]
Hey @farhad-dalirani, I am going to mark this question as resolved, based on the clarification from @kenneth-ew .
Please do give user calibration a try, for improved tracking accuracy.

If you have further doubts, please open a new issue.
